[package]
name = "malt"
version = "0.1.0"
authors = ["shintaro79 <shintaro.ishimine@aktsk.jp>"]
edition = "2018"
description = "master data integration tool"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2.27.0"
